name: Build And Deploy

on:
  push:
    branches:
      - main
      - test/ci

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  deploy:
    name: Build And Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: |
          npm ci

      # - name: generate contributors
      #   run: |
      #     bash .github/workflows/generate-contributors.sh

      - name: Build website
        env:
          NODE_OPTIONS: "--max-old-space-size=6144"
        run: |
          make build

      # https://github.com/appleboy/scp-action
      # - name: Deploy to server
      #   uses: appleboy/scp-action@v0.1.7
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USERNAME }}
      #     password: ${{ secrets.SSH_PASSWORD }}
      #     port: ${{ secrets.SSH_PORT }}
      #     source: './build/*'
      #     target: '/home/www/goframe.org'
      #     strip_components: 1
      #     rm: true

      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v4
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./build
          # cname: pages.goframe.org
